version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kcbs-buy-book"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bsqw1orz5rt4"
s3_prefix = "kcbs-buy-book"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

