AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kcbs-buy-book

Globals:
  Function:
    Timeout: 3

Resources:
  KCBSBuyBookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: buy_book/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        JSONInput:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref KCBSJsonInputBucket
            Events: "s3:ObjectCreated:*"

  KCBSJsonInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
